name: vidi9b
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ffmpeg
  - pip:
      - torch==2.3.1
      - torchvision==0.18.1
      - torchaudio==2.3.1
      - transformers==4.50.0
      - accelerate==1.5.2
      - deepspeed==0.16.4
      - sentencepiece==0.1.99
      - scikit-learn==1.2.2
      - einops==0.6.1
      - einops-exts==0.0.4
      - liger-kernel
      - peft
      - bitsandbytes
      - pydantic
      - numpy==1.26.4
      - requests
      - uvicorn
      - fastapi
      - ninja
      - wandb
      - orjson
      - opencv-python
      - decord
      - matplotlib
      - langid
      - pynvml
      - ipdb
      - tensorboard
      - moviepy
      - nvidia-ml-py3
      - httpx==0.22.0
